import "./globals.css";
import { Poppins } from "next/font/google";
import NavBar from "@/components/NavBar";

const fontFamily = Poppins({ weight: ["300", "400", "500", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={fontFamily.className}>
        <div className="flex flex-col min-h-screen antialiased">
          <header className="font-medium">
            <NavBar />
          </header>

          <div className="flex-grow">
            <div className="max-w-7xl mx-auto px-4 py-5">{children}</div>
          </div>

          <footer className="">
            <div className="text-center max-w-7xl mx-auto px-4 py-5 text-sm">
              &copy; 2023 | Made with ☕ by Krushil Naik
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
